//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 11:39:10 PM CET 
//


package resultado;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="piloto" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="posicion" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="escuderia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="vuelta_rapida" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="gp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "piloto"
})
@XmlRootElement(name = "resultado_f1")
public class ResultadoF1 {

    @XmlElement(required = true)
    protected List<ResultadoF1 .Piloto> piloto;
    @XmlAttribute(required = true)
    protected String gp;

    /**
     * Gets the value of the piloto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the piloto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPiloto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultadoF1 .Piloto }
     * 
     * 
     */
    public List<ResultadoF1 .Piloto> getPiloto() {
        if (piloto == null) {
            piloto = new ArrayList<ResultadoF1 .Piloto>();
        }
        return this.piloto;
    }

    /**
     * Gets the value of the gp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGp() {
        return gp;
    }

    /**
     * Sets the value of the gp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGp(String value) {
        this.gp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="posicion" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="escuderia" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="vuelta_rapida" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Piloto {

        @XmlAttribute(required = true)
        protected int posicion;
        @XmlAttribute(required = true)
        protected String nombre;
        @XmlAttribute
        protected String escuderia;
        @XmlAttribute(name = "vuelta_rapida")
        protected String vueltaRapida;

        /**
         * Gets the value of the posicion property.
         * 
         */
        public int getPosicion() {
            return posicion;
        }

        /**
         * Sets the value of the posicion property.
         * 
         */
        public void setPosicion(int value) {
            this.posicion = value;
        }

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the escuderia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEscuderia() {
            return escuderia;
        }

        /**
         * Sets the value of the escuderia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEscuderia(String value) {
            this.escuderia = value;
        }

        /**
         * Gets the value of the vueltaRapida property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVueltaRapida() {
            return vueltaRapida;
        }

        /**
         * Sets the value of the vueltaRapida property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVueltaRapida(String value) {
            this.vueltaRapida = value;
        }

    }

}
