//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 11:39:10 PM CET 
//


package resultado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="local" type="{http://www.misresultados.es/tds}Equipo"/>
 *         &lt;element name="visitante" type="{http://www.misresultados.es/tds}Equipo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "local",
    "visitante"
})
@XmlRootElement(name = "resultado_futbol")
public class ResultadoFutbol {

    @XmlElement(required = true)
    protected Equipo local;
    @XmlElement(required = true)
    protected Equipo visitante;

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link Equipo }
     *     
     */
    public Equipo getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equipo }
     *     
     */
    public void setLocal(Equipo value) {
        this.local = value;
    }

    /**
     * Gets the value of the visitante property.
     * 
     * @return
     *     possible object is
     *     {@link Equipo }
     *     
     */
    public Equipo getVisitante() {
        return visitante;
    }

    /**
     * Sets the value of the visitante property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equipo }
     *     
     */
    public void setVisitante(Equipo value) {
        this.visitante = value;
    }

}
