//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 11:39:10 PM CET 
//


package resultado;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tds.resultado package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tds.resultado
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultadoFutbol }
     * 
     */
    public ResultadoFutbol createResultadoFutbol() {
        return new ResultadoFutbol();
    }

    /**
     * Create an instance of {@link ResultadoF1 }
     * 
     */
    public ResultadoF1 createResultadoF1() {
        return new ResultadoF1();
    }

    /**
     * Create an instance of {@link JugadorTenis.Set }
     * 
     */
    public JugadorTenis.Set createJugadorTenisSet() {
        return new JugadorTenis.Set();
    }

    /**
     * Create an instance of {@link Goleador }
     * 
     */
    public Goleador createGoleador() {
        return new Goleador();
    }

    /**
     * Create an instance of {@link ResultadoF1 .Piloto }
     * 
     */
    public ResultadoF1 .Piloto createResultadoF1Piloto() {
        return new ResultadoF1 .Piloto();
    }

    /**
     * Create an instance of {@link Resultado }
     * 
     */
    public Resultado createResultado() {
        return new Resultado();
    }

    /**
     * Create an instance of {@link ResultadoTenis }
     * 
     */
    public ResultadoTenis createResultadoTenis() {
        return new ResultadoTenis();
    }

    /**
     * Create an instance of {@link JugadorTenis }
     * 
     */
    public JugadorTenis createJugadorTenis() {
        return new JugadorTenis();
    }

    /**
     * Create an instance of {@link Equipo }
     * 
     */
    public Equipo createEquipo() {
        return new Equipo();
    }

}
