//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 11:39:10 PM CET 
//


package resultado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Goleador complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Goleador">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="jugador" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minuto" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Goleador")
public class Goleador {

    @XmlAttribute(required = true)
    protected String jugador;
    @XmlAttribute(required = true)
    protected int minuto;

    /**
     * Gets the value of the jugador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJugador() {
        return jugador;
    }

    /**
     * Sets the value of the jugador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJugador(String value) {
        this.jugador = value;
    }

    /**
     * Gets the value of the minuto property.
     * 
     */
    public int getMinuto() {
        return minuto;
    }

    /**
     * Sets the value of the minuto property.
     * 
     */
    public void setMinuto(int value) {
        this.minuto = value;
    }

}
